In [1]:
from IPython.display import Image
from IPython.core.display import HTML

import numpy as np
import gym
import random

In [4]:
env = gym.make('FrozenLake-v1')

In [5]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [6]:
print(action_size, state_size)

4 16


In [8]:
q_table = np.zeros((state_size, action_size))

In [10]:
Image(url= 'https://cdn-media-1.freecodecamp.org/images/1*jmcVWHHbzCxDc-irBy9JTw.png')

In [11]:
total_episodes = 15000
learning_rate = 0.8
max_steps = 99
gamma = 0.95

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

In [12]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        if random.uniform(0, 1) > epsilon:
            action = np.argmax(q_table[state,:])
            
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        q_table[state, action] = q_table[state, action] + learning_rate * (reward + gamma * np.max(q_table[new_state, :]) - q_table[state, action])
        
        total_rewards += reward
        
        state = new_state
        
        if done == True:
            break
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_rewards)
    
print(f'score over time: {sum(rewards) / total_episodes}')
print(q_table)
        

score over time: 0.4740666666666667
[[1.02815781e-01 9.13233587e-02 1.11792881e-01 7.54113973e-02]
 [6.76581125e-03 2.46804392e-03 3.85940546e-02 1.12799977e-01]
 [1.49501935e-02 1.36410329e-02 7.99833434e-03 6.31978122e-02]
 [3.98255215e-03 6.89292477e-03 1.13968791e-02 2.24249185e-02]
 [2.03327622e-01 6.09812525e-02 8.45298741e-02 4.73841157e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.62455391e-02 2.40151441e-10 3.26709538e-03 2.08520538e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.31171766e-02 1.56629882e-02 6.78714533e-02 2.89793047e-01]
 [1.08203206e-02 4.83812816e-01 5.89254091e-03 1.85551267e-02]
 [7.69062443e-01 1.26192081e-03 1.49475810e-03 1.36366230e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.45945659e-02 1.27607966e-02 6.79173884e-01 1.67665891e-02]
 [2.16465164e-01 9.85274820e-01 1.91928032e-01 1.80149949e-01]
 [0.00000000e+00 0.